/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        industrial: {
          900: '#0F172A',
          800: '#1E293B',
          700: '#334155',
          600: '#475569',
          accent: '#38BDF8',
          success: '#10B981',
          warning: '#F59E0B',
          danger: '#EF4444'
        },
        "landing-bg": "#F8FAFC",
        "landing-navy": "#0B1736",
        "landing-blue": "#155EEF",
        "landing-blue-light": "#6EA8FF",
        "landing-border": "#E2E8F4",
        "landing-surface": "#F0F4FA",
        "landing-text": "#1E293B",
        "on-secondary": "#ffffff",
        "secondary-fixed": "#dce2f6",
        "on-secondary-container": "#5c6274",
        "on-primary-fixed-variant": "#003ea8",
        "on-secondary-fixed": "#151b2a",
        "on-error-container": "#93000a",
        "surface-container-lowest": "#ffffff",
        "primary-fixed": "#dbe1ff",
        "primary": "#004ac6",
        "on-error": "#ffffff",
        "surface-container-low": "#f3f3f4",
        "inverse-surface": "#2f3131",
        "border-dark": "#1E293B",
        "on-surface": "#1a1c1c",
        "on-tertiary": "#ffffff",
        "on-background": "#1a1c1c",
        "surface-container": "#eeeeee",
        "on-tertiary-container": "#d7f6ff",
        "on-tertiary-fixed": "#001f26",
        "error-container": "#ffdad6",
        "surface-bright": "#f9f9f9",
        "tertiary": "#005e6e",
        "surface-container-high": "#e8e8e8",
        "on-primary": "#ffffff",
        "on-surface-variant": "#434655",
        "surface": "#f9f9f9",
        "surface-dim": "#dadada",
        "background": "#f9f9f9",
        "surface-tint": "#0053db",
        "surface-subtle": "#F8FAFC",
        "on-tertiary-fixed-variant": "#004e5c",
        "border-light": "#E2E8F0",
        "tertiary-container": "#00788c",
        "surface-container-highest": "#e2e2e2",
        "tertiary-fixed-dim": "#4cd7f6",
        "secondary": "#585e6f",
        "secondary-container": "#d9dff4",
        "error": "#ba1a1a",
        "secondary-fixed-dim": "#c0c6da",
        "outline-variant": "#c3c6d7",
        "on-secondary-fixed-variant": "#404757",
        "on-primary-fixed": "#00174b",
        "primary-fixed-dim": "#b4c5ff",
        "primary-container": "#2563eb",
        "inverse-primary": "#b4c5ff",
        "tertiary-fixed": "#acedff",
        "inverse-on-surface": "#f0f1f1",
        "outline": "#737686",
        "surface-variant": "#e2e2e2",
        "on-primary-container": "#eeefff"
      },
      spacing: {
        "margin-mobile": "16px",
        "md": "16px",
        "unit": "4px",
        "gutter": "24px",
        "sm": "8px",
        "xs": "4px",
        "lg": "24px",
        "xl": "40px",
        "margin-desktop": "32px"
      },
      fontFamily: {
        "headline-lg": ["Inter"],
        "label-md": ["Inter"],
        "body-sm": ["Inter"],
        "body-md": ["Inter"],
        "headline-md": ["Inter"],
        "body-lg": ["Inter"],
        "display-lg": ["Inter"],
        "headline-lg-mobile": ["Inter"]
      },
      fontSize: {
        "headline-lg": ["32px", { "lineHeight": "40px", "letterSpacing": "-0.01em", "fontWeight": "600" }],
        "label-md": ["12px", { "lineHeight": "16px", "letterSpacing": "0.05em", "fontWeight": "600" }],
        "body-sm": ["14px", { "lineHeight": "20px", "fontWeight": "400" }],
        "body-md": ["16px", { "lineHeight": "24px", "fontWeight": "400" }],
        "headline-md": ["24px", { "lineHeight": "32px", "fontWeight": "600" }],
        "body-lg": ["18px", { "lineHeight": "28px", "fontWeight": "400" }],
        "display-lg": ["48px", { "lineHeight": "56px", "letterSpacing": "-0.02em", "fontWeight": "700" }],
        "headline-lg-mobile": ["24px", { "lineHeight": "32px", "letterSpacing": "-0.01em", "fontWeight": "600" }]
      }
    },
  },
  plugins: [],
}
